### ISSUE TITLE
After installing the matrix.org adapter 0.0.7 the admin ui throw an error

### ISSUE THREAD

**Issue by tardar** [oelison/ioBroker.matrix-org#8]
**Describe the bug**  
After installing the matrix.org adapter 0.0.7 the admin ui throw an error

**To Reproduce**  
1. Go to 'Adapter'
2. Click on 'Install matrix.org adapter instance'
3. The admin UI reloads

**Expected behavior**  
The admin ui reloads and show all the admin stuff in there

**Screenshots & Logfiles**  
Error after install and open console after error occurs:
`TypeError: Cannot read properties of undefined (reading 'value')
    at vn.renderItem (ConfigText.jsx:36:34)
    at vn.render (ConfigGeneric.jsx:514:39)
    at Wi (react-dom.production.min.js:204:189)
    at Rs (react-dom.production.min.js:203:149)
    at oa (react-dom.production.min.js:292:172)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:124`

After refreshing the page with the console opened:
`TypeError: Cannot read properties of undefined (reading 'value')
    at vn.renderItem (ConfigText.jsx:36:34)
    at vn.render (ConfigGeneric.jsx:514:39)
    at Wi (react-dom.production.min.js:204:189)
    at Rs (react-dom.production.min.js:203:149)
    at oa (react-dom.production.min.js:292:172)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:124
Hi @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
bs @ react-dom.production.min.js:269
Ln @ scheduler.production.min.js:13
Gn @ scheduler.production.min.js:14`

![2022-07-30_08-43-30](https://user-images.githubusercontent.com/40645000/181878373-fe11ab99-6f5a-479d-af9a-a295b48ec763.jpg)

**Versions:**  
 - Adapter version: matrix.org 0.0.6
 - JS-Controller version: 4.0.23
 - Node version: 16.16.0
 - Operating system: 5.10.0-16-amd64 #1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux

**Comment by oelison** [comment]
Hi. I Text to investigate here. Please check the given version. Title says V0.0.7 and end of description says V0.0.6. I think you mean V0.0.7. There I have removed all react stuff. So may be that the upgrade will make struggling the GUI. Please try to deinstall V0.0.7 and reinstall and give me a feedback. I'm new with developing adapter for ioBroker, but the community is very helpful.

**Comment by oelison** [comment]
Please give me the admin version.

**Comment by tardar** [comment]
Hey and a good morning :)
I installed it fresh from the repo and there the 0.0.6 was listed.
After the install and check from console it shows me the 0.0.7 - so i think the 0.0.7 is installed.
The admin version is 6.2.11

It seems that the error has gone - so i think he installed the 0.0.6 and updated automatically ?
I checked this a few minutes ago.

**Comment by oelison** [comment]
admin version is 6.2.11
https://github.com/ioBroker/ioBroker.admin/issues/1624 will be closed.
I will left this open until 7th Aug. 2022. Please comment if someone get similar issue!

**Comment by oelison** [comment]
No reported again.
